### ISSUE TITLE
Bug : Overlapp of elements

### ISSUE THREAD

**Issue by Anjaliavv51** [MLSA-AVV-Amaravati/MLSA-AVV-Amaravati.github.io#1]
![image](https://github.com/MLSA-AVV-Amaravati/MLSA-AVV-Amaravati.github.io/assets/154777864/c4773bdd-d0e2-42bd-bfcc-fe08d0f8bb6b)

**Comment by Anjaliavv51** [comment]
![image](https://github.com/user-attachments/assets/1ae584dd-85fc-43af-83b6-77882ef5aa36)

**Comment by Anjaliavv51** [comment]
@Polymath-Saksh please assign me this issue.

**Comment by Polymath-Saksh** [comment]
Hi,

The project is in archive state. No changes needed.

Regards,
Saksham Kumar

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Polymath-Saksh** [comment]
Project Archived.
